### ISSUE TITLE
Logo not responsive

### ISSUE THREAD

**Issue by anmolcool007** [anmolcool007/snippet#1]

**Comment by hn4733** [comment]
I've made the logo responsive for screens below 700px (you can adjust if needed). Please check out my PR.

**Comment by anmolcool007** [comment]
Tested and Merged.

Can you please make the same changes in the typography CSS file as well?

**Comment by hn4733** [comment]
Okay, I've adjusted the typography stylesheet as well. I've also resolved the overflow issue of the headings within the typography section as stated on #2

**Comment by anmolcool007** [comment]
Thank you for your contributions.

Closing this issue.
