### ISSUE TITLE
Improving Navbar Style in Template files

### ISSUE THREAD

**Issue by anmolcool007** [anmolcool007/snippet#10]
## Issue [Required]

Navbar element positioning problem in different screen sizes

## Description [Required]

The spacing between logo and GitHub icon, home button does not look good in smaller screen sizes.
![aa](https://user-images.githubusercontent.com/43794036/97092309-bc7e5700-1660-11eb-89ec-369f8b5e8c6e.PNG)
![bb](https://user-images.githubusercontent.com/43794036/97092311-be481a80-1660-11eb-9ed9-40a3765e7905.PNG)

## Issue targets:

* [ ] Adding new CSS styles
* [x] Improving existing template
* [ ] Changing JS filw for better dynamics
* [ ] Other

## Steps to Reproduce [In case of a Bug]

1. Go to https://anmolcool007.github.io/snippet/
2. Change to phone view

## Expected
Good looking navbar with proper spacing in both home and typography page.

**Comment by harjotkarwal** [comment]
> Navbar element positioning problem in different screen sizes

Fixed in #11
