### ISSUE TITLE
neon-flikr typography is overflowing in mobile view 

### ISSUE THREAD

**Issue by Tanuj22** [anmolcool007/snippet#2]
![Screenshot from 2020-10-24 00-22-08](https://user-images.githubusercontent.com/42486853/97042755-22021300-158f-11eb-9715-1a4826b6d193.png)

**Comment by anmolcool007** [comment]
We can Wrap the design display in a div stage and edit its media query in CSS.

Interested people can pick this up.

**Comment by harjotkarwal** [comment]
I think I can help you to keep the text in box. Can you assign me for this task and this is my second day with Hacktoberfest for first time.

**Comment by anmolcool007** [comment]
Sure @harjotkarwal go ahead.

If possible I would suggest you to use bootstrap instead of hardcoding the media queries in CSS.
Issue of incorporating bootstrap raised in https://github.com/anmolcool007/snippet/issues/6#

**Comment by anmolcool007** [comment]
@harjotkarwal 

> I think I can help you to keep the text in box. Can you assign me for this task and this is my second day with Hacktoberfest for first time.

This issue was solved in PR #9 
You can still add bootstrap for better functioning 
(or) Improve spacing in the navbar between headings and buttons

**Comment by harjotkarwal** [comment]
Can you please create an issue so it will count as my  Hacktoberfest PR and it would be easy for me to figure out the exact location you want me to fix.

**Comment by anmolcool007** [comment]
@harjotkarwal follow-up issue [#10] created. 

Closing this issue as of now.
