### ISSUE TITLE
Add a issue and PR template

### ISSUE THREAD

**Issue by Tanuj22** [anmolcool007/snippet#7]
Adding an issue and PR template will help in better understanding and help bring uniformity.

**Comment by anmolcool007** [comment]
Thank you for the suggestion

Issue Template [de867a2] and Pull Request Template [1660854] have been created.
Please suggest any further changes (if any).

**Comment by Tanuj22** [comment]
LGTM

**Comment by anmolcool007** [comment]
Great!!

Closing this issue.

**Comment by harjotkarwal** [comment]
I have added new effect. #12
